djangoauth/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from djangoauth.main import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls'))
	# url(r'^$', views.IndexView.as_view(), name='index'),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = "main" # Used for differentiating between different apps on a project (when using {% url %} tag for example)
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    # url(r'^register/$', views.register, name='register'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    (url(r'^profile/(?P<pk>[0-9]+)$', views.ProfileView.as_view(), name='profile'))
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
	def __str__(self):
		return self.user.get_full_name() + " | " + self.user.email;
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	bio = models.TextField(max_length=500, blank=True)
	url = models.CharField(max_length=500, blank=True)
	location = models.CharField(max_length=30, blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('url', 'location', 'bio')

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import generic;
from django.http import HttpResponse, HttpResponseRedirect

from .forms import UserForm, ProfileForm

class IndexView(generic.ListView):
	template_name = "main/index.html"
	context_object_name = 'users';
	def get_queryset(self):
		return User.objects.all();

class RegisterView(generic.FormView):
	template_name = 'main/register.html';
	form_class = UserCreationForm;
	success_url = '/';
	def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
		user = form.save()
		messages.success(self.request, 'Your account was successfully created! You can now login')
		return HttpResponseRedirect(self.success_url)

class ProfileView(generic.DetailView):
	model = User;
	template_name = "main/profile.html";
	context_object_name = 'profile_user';

# An alternate, non generic.DetailView profile view method, for my notes.
# def profile(request, user_id):
#	profile_user = get_object_or_404(User, pk=user_id);
#	return render(request, 'profile.html',{'profile_user':profile_user})
#

@login_required
def edit_profile(request):
	if request.method == 'POST':
		user_form = UserForm(request.POST, instance=request.user)
		profile_form = ProfileForm(request.POST, instance=request.user.profile)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, 'Your profile was successfully updated!')
			return redirect('main:edit_profile')
		else:
			messages.error(request, 'Please correct the error below.')
	else:
		user_form = UserForm(instance=request.user)
		profile_form = ProfileForm(instance=request.user.profile)
	return render(request, 'main/edit_profile.html', {
		'user_form': user_form,
		'profile_form': profile_form
	})

main/templates/main/edit_profile.html
{% extends 'main/header.html' %}


{% block content %}
	<h2>Editing {{user.username}}'s Profile</h2>
	<form method="post">
		{% csrf_token %}
		{{user_form.as_p}}
		{{profile_form.as_p}}
		<button type="submit">Update</submit>
	</form>
{% endblock %}

main/templates/main/header.html
<!DOCTYPE html>
<html>
<head>
	<title>Proof that I can code Django 2.11 on Python 2.7</title>
</head>
<body>
	<a href = "{% url 'main:index' %}">Home</a>
	{% if user.is_authenticated %}
		<a href = "{% url 'main:logout' %}">Log out</a>
	{% else %} 
		<a href = "{% url 'main:register' %}">Register</a>
		<a href = "{% url 'main:login' %}">Log In</a>
	{% endif %}
	<hr>
	{% if messages %}
		<!-- <ul class="messages"> -->
			{% for message in messages %}
			<p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
			{% endfor %}
		<!-- </ul> -->
	{% endif %}
	{% block content %}
	{% endblock %}
</body>
</html>

main/templates/main/index.html
{% extends 'main/header.html' %}

{% block content %}
	<h2>Registered Users ({{users.count}} total)</h2>
	{% if users %}
	    <ul>
	    {% for user in users %}
	        <!-- <li><a href="{% url 'main:index' %}">{{ user.username }}</a></li> -->
			<li><a href="{% url 'main:profile' user.id %}">{{ user.username }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No users have signed up!</p>
	{% endif %}
	{% if user.is_authenticated %}
		<h3>You are logged in as: {{ user.username }}. <a href="{%url 'main:edit_profile' %}">Edit Profile</a></h3>
	{% else %} 
		<h3>You are not logged in.</h3>
	{% endif %}
{% endblock %}

main/templates/main/profile.html
{% extends 'main/header.html' %}

{% block content %}
	<h2>Viewing {{profile_user.username}}'s Profile</h2>
	<ul>
		<li>Full Name: {{ profile_user.get_full_name }}</li>
		<li>Email: {{ profile_user.email }}</li>
		<li>Bio: {{profile_user.profile.bio}}</li>
		<li>URL: {{profile_user.profile.url}}</li>
		<li>Location: {{ profile_user.profile.location }}</li>
	</ul>
{% endblock %}

main/templates/main/register.html
{% extends 'main/header.html' %}

{% block content %}
	<h2>Register</h2>
	<form method="post">
		{%csrf_token %}
		{{form.as_p}}
		<button type="submit">Register</button>
	</form>
{% endblock %}